version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    hostname: db-sisampah
    networks:
      - backend-network
  backend:
    image: backend
    build: .
    volumes:
      - ./:/backend
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    hostname: api-sisampah
    networks:
      - backend-network
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6380:6379
    hostname: redis-sisampah
    volumes:
      - ./redis:/data
    networks:
      - backend-network
networks:
  backend-network:
    driver: bridge

    
    